FROM python:3.10-slim
WORKDIR /app
COPY services/window_collector/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip uninstall -y kafka || true \
 && pip install --no-cache-dir kafka-python==2.0.2
COPY services/window_collector/ .
CMD ["python", "main.py"]
