FROM python:3.11
WORKDIR /app
COPY services/window_loader/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY services/window_loader/ .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8081"]
